const privacyPolicyData = [
    {
        title: "1. Introduction",
        content: ` Welcome to the Privacy Policy of Mpluse Fintech Private Limited (“Mpluse”). We treat your personal data—such as your identity, contact details, transaction history, technical usage information, and KYC documents—with the highest level of confidentiality and security. We collect this information to verify your identity, process and reconcile transactions, comply with legal and regulatory requirements (IT Act, 2000; DPDP Act, 2023; RBI/NPCI guidelines), prevent fraud, and continually improve our services. Data may come directly from you, automatically via our websites, apps, or APIs, or from our trusted banking and analytics partners. We protect your information using industry-standard measures (TLS encryption, AES-256 storage, role-based access controls, intrusion detection) and never sell it to third parties. By using our services, you consent to these practices. If you have questions or wish to withdraw your consent, please contact our Data Protection Officer`
        },
        {
        title: "2. Information We Collect and How We Use It",
        content: ` Mpluse Fintech Private Limited (“Mpluse,” “we,” “us,” or “our”) collects and processes certain personal data in order to provide and secure our services, comply with applicable laws, and maintain the integrity of our platform. When you register on our primary portal (dashboard.mpluse.in), developer portal (developer.mpluse.in), or sandbox environment, we obtain your full name, email address, telephone number, company name and postal address so that we can verify your identity, authenticate your account, deliver important service notifications and offer timely technical or customer support. To execute and reconcile payouts (IMPS, UPI) and collection requests, we record your bank account details, UPI ID, transaction amounts, timestamps and identifiers, as well as wallet balances, thereby ensuring accurate payment processing, refund handling and audit-trail maintenance. In order to meet our KYC/AML responsibilities under the Information Technology Act, 2000, the Digital Personal Data Protection Act, 2023, and RBI/NPCI guidelines, we securely collect and encrypt sensitive regulatory documents such as PAN, Aadhaar, GST certificates, company PAN and e-signatures, protecting against fraud and facilitating legal compliance. Whenever you interact with our websites, applications or APIs, we also automatically capture technical and usage information—your IP address, device or browser type, operating system, API call metrics, server logs and cookie data—to help us enhance system performance, diagnose and resolve issues, detect and prevent security threats (including intrusion and DDoS attacks) and optimize your overall user experience. Additionally, under strict confidentiality agreements with our trusted banking partners, the NPCI network, payment gateways and analytics providers, we may receive supplementary information — such as credit scores, fraud alerts and transaction confirmations—to support advanced risk assessments and verify financial profiles. All personal data processing is governed by applicable Indian laws (IT Act, 2000; DPDP Act, 2023; RBI/NPCI guidelines) and, where relevant, international standards (GDPR, PCI-DSS). We never sell your information to unaffiliated third parties, and we retain it only for as long as necessary to fulfill the purposes described above, after which it is securely deleted or anonymized`
        },
        {
        title: "3. Data Retention",
        content: `Personal data is retained only as long as necessary. Account data: up to 24 months post-deactivation. Financial records: at least 7 years (per RBI and Income Tax Act). KYC documents: at least 7 years. Technical logs and cookies: up to 24 months. Marketing consents: until withdrawn or 3 years after last interaction. All data is encrypted and access-controlled, and deleted/anonymized after expiration.`
        },
        {
        title: "4. Disclaimer & No Warranty",
        content: `The content, information, materials, and any software made available on this website (including our primary portal at dashboard.mpluse.in, developer portal at developer.mpluse.in, and sandbox environment) are provided on an “as is” and “as available” basis. Mpluse Fintech Private Limited (“Mpluse,” “we,” “us,” or “our”) makes no representations or warranties, express or implied, regarding the accuracy, completeness, merchantability, fitness for a particular purpose, or non-infringement of third-party rights. While we employ commercially reasonable measures—such as TLS encryption for data in transit, AES-256 encryption at rest, firewalls, intrusion-detection systems, and regular security audits— to keep our platforms free from unauthorized access, viruses, and other security threats, we cannot guarantee that our websites, applications, APIs, or databases will be entirely free of vulnerabilities or cyber-attacks. Similarly, we cannot warrant that any information you transmit to us over the internet will not be intercepted or compromised. By using our services, you acknowledge and agree that your use is at your sole risk, and Mpluse shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your access to or use of the website, even if advised of the possibility of such damages`
        },
        {
        title: "5. Policy Updates & Responsibilities",
        content: ` We may revise this Privacy Policy at any time without prior notice. To stay informed of any changes, please review this document periodically; all updates will take effect immediately for all users. You are responsible for keeping your personal information—especially your current e-mail address—accurate and up to date. If you do not agree with any revision to the way we process your data, you must promptly notify us at privacy@mpluse.in to request account deactivation. Continued use of our websites, applications, APIs, or dashboards after any such update will constitute your acceptance of, and agreement to be bound by, the revised terms`
        },
        {
        title: "6. Children’s Privacy",
        content: ` Our services are not intended for individuals under the age of 18, and we do not knowingly collect personal data from minors. If we discover that we have inadvertently received personal data from a child under 18, we will promptly delete that information from our systems. Parents or legal guardians who become aware that their child has provided us with personal data without their consent should contact our Data Protection Officer at privacy@mpluse.in. Upon verification of your request, we will take all reasonable steps to remove the child’s personal information from our records. We encourage parents and guardians to monitor their children’s online activities and to help enforce our Privacy Policy by instructing their children never to provide personal data through our websites, applications, APIs, or dashboards without parental permission.`
        },
        {
        title: "7. Your Rights",
        content: ` You may always ask us to confirm whether we process your personal data and to explain the reasons, categories, recipients, and retention periods involved. You can obtain a complete copy of your data in a structured, machine-readable format and, where technically feasible, request that we transfer it directly to another service provider. If any information we hold is inaccurate, incomplete, or outdated, you have the right to have it corrected or updated without undue delay. When your data is no longer required for the purpose it was collected—or if you withdraw your consent and no other legal basis for processing exists—you may ask us to erase it, subject to our statutory obligations under laws such as the RBI or Income-tax Act. You may also request that we suspend or restrict processing while we verify accuracy or if you object to certain uses, especially marketing communications. Withdrawing consent to any processing activity will not affect the lawfulness of actions taken before your withdrawal. To exercise any of these rights, simply email your request to our Data Protection Officer at privacy@mpluse.in; we will acknowledge receipt within seven business days and aim to complete our response within thirty calendar days at no cost to you, unless your request is manifestly unfounded or excessive, in which case we may charge a reasonable fee. If you are not satisfied with our handling of your request, you have the right to lodge a complaint with the Office of the Data Protection Authority under the Digital Personal Data Protection Act, 2023.`
        },
        {
        title: "8. Scope & Applicability",
        content: `This Privacy Policy governs the handling of all personal data collected or processed in connection with your use of our digital platforms—including the primary portal (dashboard.mpluse.in), developer portal (developer.mpluse.in), sandbox environment, mobile applications, APIs and dashboards—and the full range of services we offer, such as API-based payouts and collections (IMPS, UPI, BBPS), wallet management, Banking-as-a-Service integrations, transaction monitoring and webhook notifications, as well as value-added features like recharge and ticketing. It applies to every individual whose information we handle— merchants, enterprise partners, end-users, employees, contractors or others—and to data obtained directly from you (e.g., during registration, KYC/AML onboarding or support requests), automatically via cookies, server logs and analytics, or received under confidentiality agreements from regulated banking and analytics partners This Policy covers personal data relating to individuals located in India and any other jurisdictions where our operations or data transfers occur, always in compliance with applicable local requirements. Although our third-party financial institutions and service providers maintain their own privacy practices, we require them to uphold safeguards at least as rigorous as those described here.`
        },
        {
        title: "9. Detailed Security Measures",
        content: ` We protect your data at every layer of our cloud infrastructure. All traffic between your device and our systems is encrypted using TLS 1.2+ to prevent interception, and data stored within our environment is secured with AES-256 encryption under a managed key-management service. Access to production servers is tightly restricted by role-based permissions and enforced multi factor authentication, ensuring that only authorized personnel can view or modify sensitive information. Our network perimeter is defended by cloud-native firewalls, security groups, and DDoS mitigation services that block unauthorized traffic. Behind the scenes, centralized logging captures every sign-in, configuration change, and system event—triggering real-time alerts for unusual or suspicious activity. To uncover hidden risks, we run automated vulnerability scans on a weekly basis and engage accredited third-party experts to perform annual penetration tests, remediating any findings before they can be exploited. We maintain encrypted backups in a separate geographical region and conduct regular recovery drills to validate our disaster-recovery procedures. Should an incident occur, a documented escalation process guides our rapid response: containing the issue, assessing impact, notifying regulators if required, and communicating with affected users. Every cloud and security vendor we partner with must adhere to stringent data-protection agreements and submit to periodic compliance audits, so that these external controls match or exceed our own rigorous standards.`
        },
        {
        title: "10. Service Providers & Processors",
        content: ` To deliver and maintain our suite of financial and technology services, we partner with a carefully selected network of third-party service providers and data processors. These external entities perform critical functions—from hosting our cloud infrastructure and processing payments to sending notifications, analyzing usage patterns, and providing customer-support tools. Before engaging any service provider, we conduct a comprehensive due-diligence review that examines their security posture, privacy practices, and compliance with relevant laws and standards. Each provider must enter into a formal Data Processing Agreement (DPA) with us, which clearly defines the scope of permitted processing, prohibits any use of your personal data beyond our instructions, and requires strict confidentiality. Under the DPA, providers are contractually obligated to implement technical and organizational safeguards—such as end-to-end encryption, role-based access controls, secure key management, and regular vulnerability assessments—that align with the Information Technology Act, 2000; the Digital Personal Data Protection Act, 2023; and RBI/NPCI guidelines. Once onboarded, our team maintains continuous oversight through regular compliance assessments. We review third-party audit reports—such as SOC 2 Type II or ISO 27001 certifications—evaluate findings from penetration tests, and verify remediation plans for any identified vulnerabilities. We employ tailored security questionnaires and, where necessary, exercise our contractual right to conduct on-site or remote security audits. In the event of a security incident involving a service provider, we require immediate notification, rapid containment measures, and a formal report on root-cause analysis and corrective actions. When a provider’s services are no longer required, or at the end of our contractual relationship, we enforce secure data-removal procedures: all personal data held by the provider must be returned to us or permanently deleted in accordance with our retention and disposal policies. By applying these layered controls and ongoing monitoring practices, we ensure that your information remains protected to the same high standard you expect from Mpluse—even when it is entrusted to our external partners`
        },
        {
        title: "11. Cookies & Tracking Technologies",
        content: ` Cookies and tracking technologies on our developer portals and sandbox environments are deployed solely to ensure secure, seamless, and performant access to Mpluse’s API infrastructure. When you authenticate, a short-lived session cookie is created to maintain your login state and embed anti-CSRF tokens, preventing unauthorized requests and session hijacking. We also use encrypted, first-party persistent cookies to remember innocuous preferences—such as interface theme, language, or dashboard layout—so you don’t need to reconfigure settings each time you log in. These cookies carry no personal identifiers and expire automatically once they no longer serve their function. Behind the scenes, lightweight analytics scripts collect only aggregated, anonymized metrics— API call volumes, average response times, error rates, and peak usage patterns—to help our engineering teams identify performance bottlenecks, predict capacity needs, and detect unusual behavior that could signal abuse or fraud. No third-party cookies or cross-site trackers are permitted on our platforms; all tracking is performed in-house under strict adherence to the Digital Personal Data Protection Act, 2023 and RBI/NPCI guidelines. You retain full control: non essential cookies can be disabled at any time via your browser settings or through our Cookie Preferences panel, and any change is honored immediately without impairing your ability to use core API and dashboard functions`
        },
        {
        title: "12. Legal Basis for Processing",
        content: ` Cookies and tracking technologies on our developer portals and sandbox environments are  deployed solely to ensure secure, seamless, and performant access to Mpluse’s API  infrastructure. When you authenticate, a short-lived session cookie is created to maintain your  login state and embed anti-CSRF tokens, preventing unauthorized requests and session  hijacking. We also use encrypted, first-party persistent cookies to remember innocuous  preferences—such as interface theme, language, or dashboard layout—so you don’t need to  reconfigure settings each time you log in. These cookies carry no personal identifiers and expire  automatically once they no longer serve their function. Behind the scenes, lightweight analytics scripts collect only aggregated, anonymized metrics—  API call volumes, average response times, error rates, and peak usage patterns—to help our  engineering teams identify performance bottlenecks, predict capacity needs, and detect  unusual behavior that could signal abuse or fraud. No third-party cookies or cross-site trackers  are permitted on our platforms; all tracking is performed in-house under strict adherence to the  Digital Personal Data Protection Act, 2023 and RBI/NPCI guidelines. You retain full control: non essential cookies can be disabled at any time via your browser settings or through our Cookie  Preferences panel, and any change is honored immediately without impairing your ability to use  core API and dashboard functions.`
        },
        {
        title: "13. Third-Party Links & External Services",
        content: ` While Mpluse’s developer portal and sandbox environment serve as the secure hub for all your  API-based banking needs, you may occasionally be directed to external websites or embedded  services that we partner with—such as regulated bank portals for account verification, payment gateway dashboards for transaction settlement, analytics platforms for detailed usage insights,  or notification services for e-mail and SMS delivery. These third-party links and integrations exist  to provide the full breadth of Banking-as-a-Service functionality you expect from Mpluse, but  once you leave our domain, you enter an environment governed by that provider’s own security  controls and privacy policy.  Because each partner maintains its own data-handling practices, Mpluse cannot guarantee the  confidentiality or regulatory compliance of external sites; we neither control their content nor  assume liability for their operation. We therefore strongly encourage you to review the privacy  notice and terms of service of any third party before sharing personal information. By making  these distinctions clear, we preserve the transparency and trust at the core of our API  infrastructure, ensuring you remain fully informed about where your data travels and who is  responsible for its protection at every step`
        },
        {
        title: "14. Data Breach Notification",
        content: ` In the event that we detect any unauthorized access, disclosure, alteration or destruction of personal data—collectively referred to as a “data breach”—we will initiate our incident response procedures without delay. Our security team will immediately contain the incident, analyze system logs and forensic data to determine its scope and root cause, and implement technical measures to prevent further unauthorized activity. Within 72 hours of confirming a breach, we will notify both the affected individuals and the relevant regulatory authorities (in accordance with the Digital Personal Data Protection Act, 2023 and RBI/NPCI guidelines). Each notification will include a clear summary of the incident (what happened and when), the categories of personal data involved, the potential risks to data subjects, and the specific steps we have taken to mitigate harm. We will also provide recommended actions you can take—such as changing your password, enabling multi-factor authentication, monitoring account statements, and being vigilant against phishing attempts. Following the initial notification, we will produce a comprehensive post-incident report detailing our findings, corrective and preventive measures, and any updates to our security policies or controls designed to avert future breaches. Throughout this process, we remain committed to full transparency and will keep you informed of our progress until your data’s integrity and confidentiality are fully restored`
        },
        {
        title: "15. Complaints & Dispute Resolution",
        content: ` If you ever believe that Mpluse has mishandled your personal data—whether due to an error in  processing, a delayed response to your request, or any perceived breach of your privacy rights—  you can follow our structured resolution process. First, email a detailed description of your  concern, including any relevant transaction or reference numbers, to our Data Protection  Officer at privacy@mpluse.in. We will acknowledge receipt of your complaint within seven  business days and may request further information to fully understand and investigate the  issue.  Our team will then undertake an internal review, consulting technical and legal specialists as  needed, and determine the appropriate corrective actions—such as updating or deleting  information, strengthening our procedures, or clarifying our practices. You will receive progress  updates at key milestones, usually within 15 days of filing, so you remain informed about the  status of your case. We strive to deliver a comprehensive written response and resolution within  thirty calendar days.  If you are not satisfied with our resolution, you may escalate your complaint to the Office of the  Data Protection Authority under the Digital Personal Data Protection Act, 2023, or for banking related issues to the RBI Grievance Redressal Cell. Should these avenues fail to resolve your  concern, you are entitled to pursue mediation or arbitration under applicable Indian laws.  Throughout this entire process, we maintain a formal complaint register, record root-cause  analyses and remediation plans, and use your feedback to continuously enhance our policies,  procedures, and security controls—ensuring that every grievance is taken seriously, addressed  promptly, and used as an opportunity to reinforce your trust in Mpluse.`
        },
        {
        title: "16. Data Protection Officer",
        content: ` For any questions, requests or concerns about how your personal data is handled, please contact our Data Protection Officer at: Email: privacy@mpluse.in Phone: [Your support or DPO phone number here] Address: [Your registered office address here] Our Data Protection Officer is available Monday through Friday, 9:00 AM–6:00 PM IST, and will acknowledge receipt of your inquiry within seven business days. Whether you wish to exercise your data-subject rights, report a suspected breach, or seek clarification on our practices, please feel free to reach out—your privacy is our priority`
        },
        {
        title: "17. Contact Information",
        content: `Email: privacy@mpluse.in\nPhone: 011-69046382\ncorporate address : 119, Lane Number 11, New Defence Colony Uttaretiya Lucknow 226025`
        }
    ];

export default privacyPolicyData