// src/data/termsData.js

import { title } from "framer-motion/client";




const termsData = [
    {
        title: "1. Acceptance of Terms",
        content: `By accessing or using any of Mpluse Fintech Private Limited’s (“Mpluse, ” “we, ” “us, ” or “our”) services—including the dashboard, developer portal, sandbox environment, APIs, mobile applications, or any related interfaces—you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions and our Privacy Policy. Your use of Mpluse’s services constitutes your express acceptance of these terms. If you do not agree with any provision herein, you must immediately discontinue all access to and use of our services. These Terms, together with any documents they expressly incorporate, form the entire agreement between you and Mpluse regarding your use of the services, superseding any prior understandings or agreements.`,
    },
    {
        title: "2. Definitions",
        content: `In these Terms and Conditions, “Services” means all offerings made available by Mpluse Fintech Private Limited—whether the dashboard, developer portal, sandbox environment, RESTful APIs, webhooks, mobile applications or any related features. “You” or “User” refers to any individual or legal entity that registers for or otherwise accesses and uses the Services, and your “Account” is the user profile you create (including your unique login credentials, configuration settings, and profile information) to access those Services. “Credentials” are the API keys, secret keys, tokens or passwords issued or generated by Mpluse for authenticating your API calls, while “Documentation” comprises the technical guides, reference manuals, sample integrations, SDKs and other materials provided by Mpluse to help you integrate with and use our Infrastructure. All data, content or information you submit, transmit or process through the Services—such as transaction details, customer records or metadata—is collectively your “User Data, ” and any non-public information shared between you and Mpluse—such as business plans, technical specifications or pricing—constitutes “Confidential Information.” These Terms (including any documents they expressly incorporate by reference, like our Privacy Policy or applicable Service Level Agreements) became binding on the “Effective Date, ” which is the date you first accepted them or the date they were first made available to you, whichever occurs earlier. Finally, any claim, controversy or disagreement arising out of or relating to these Terms or your use of the Services is referred to as a “Dispute.”`,
    },
    {
        title: "3. Eligibility & Account Registration",
        content: `To access and use Mpluse’s API infrastructure, you must be either (a) a legally registered business entity in India or (b) an individual aged 18 years or older acting in connection with your professional or commercial activities. By registering for an account, you represent and warrant that you meet these eligibility requirements and possess the legal authority to bind your organization to these Terms and Conditions. Registration takes place through our developer portal, where you will be asked to provide accurate and complete information, including your full name, business name, registered address, email address, and any KYC/AML documentation required under applicable laws and RBI/NPCI guidelines. You agree to maintain and promptly update your account information— such as contact details and bank account data—so that we can continue to provide you with secure and uninterrupted service. Upon submission, Mpluse reserves the right to verify your identity and supporting documents before activating your account. We may also perform background checks or request additional information at any time to ensure compliance with our policies and regulatory obligations. Account activation, suspension, or termination decisions rest solely with Mpluse, and we will notify you of any change in status via the email address associated with your account. API Access, Keys & Security Once your account is active, you will receive unique API credentials (keys and tokens) and access to the sandbox environment for testing. It is your responsibility to safeguard these credentials and to immediately inform Mpluse of any unauthorized use or potential security breach. You may not share your credentials with any third party or use them for purposes outside the scope of our services. Failure to adhere to these requirements may result in suspension or revocation of your access. `,
    },
    {
        title: "4. API Access, Keys & Security",
        content: `When your Mpluse account is approved, you will receive a pair of unique API credentials—an API Key and Secret—along with access to separate sandbox and production endpoints. These credentials authenticate every request you make and must be included in each API call according to our documentation. You are solely responsible for safeguarding your API Key and Secret: never embed them in client‐side code, public repositories, or URLs. If you believe your credentials have been compromised, you must immediately revoke them via the developer portal and notify us at security@mpluse.in so we can investigate and issue replacements. All API traffic is encrypted in transit using TLS 1.2 or higher, and access is further protected by anti‐replay measures and rate limiting. Mpluse logs every request, including timestamp, origin IP, endpoint accessed, and response status, to help detect unusual patterns or potential abuse. We recommend rotating your API Secret on a regular cadence (e.g. every 90 days) and after any personnel change. Mpluse reserves the right to suspend or revoke any credentials at our discretion—particularly if we detect suspicious activity or a breach of these Terms. By using our APIs, you agree to follow these security practices and cooperate fully with any investigation into unauthorized access.`,
    },
    {
        title: "5. Permitted Use of Services",
        content: `Your use of Mpluse’s API-based Services is strictly limited to integrating, developing, testing, and operating your own business applications or delivering direct value to your end customers. Through our published RESTful endpoints, you may initiate and reconcile IMPS, UPI, and BBPS payouts and collections, manage virtual wallet balances, retrieve transaction histories and realtime analytics, and generate compliance or reconciliation reports exactly as described in our Documentation. All requests must be authenticated with your issued API credentials and must adhere to our specified rate limits, TLS encryption, anti-CSRF tokens, and logging controls. You may use these Services only for lawful business purposes and in full compliance with all applicable laws and regulations, including KYC/AML requirements, RBI/NPCI guidelines, and the Digital Personal Data Protection Act, 2023. Any attempt to reverse-engineer our APIs, scrape or cache data beyond permitted limits, resell or sublicense the Services as a standalone product, overload or disrupt our infrastructure, or facilitate unlawful activity is strictly prohibited and may result in immediate suspension or termination of your access. If you are uncertain whether a specific integration or workflow is permitted, please review our Documentation or contact support@mpluse.in for clarification before proceeding.`,
    },
    {
        title: "6. Prohibited Activities",
        content: `You agree not to use Mpluse’s Services for any unlawful or abusive purpose, and in particular you will not (a) attempt to gain unauthorized access to our systems, endpoints or data; (b) reverse-engineer, decompile or disassemble any portion of our APIs or underlying software; (c) scrape, crawl, cache or mine any data beyond the limits permitted by our rate limits and Documentation; (d) submit false or fraudulent KYC, transaction or identity information; (e) facilitate money laundering, terrorism financing or other illicit activity; (f) overload, disrupt or impair the integrity or performance of our infrastructure (including by launching denial-ofservice attacks); (g) resell, sublicense or bundle the Services as a standalone product; (h) use automated means to create or manage multiple accounts without our prior written consent; or (i) send spam, phishing or unsolicited marketing communications via our platform. Any prohibited conduct may result in immediate suspension or termination of your access and may expose you to legal liability`,
    },
    {
        title: "Service Levels & Availability",
        content: ` Mpluse is dedicated to providing a robust, always-on API infrastructure for your Banking-as-a Service needs. We target 99.9% uptime on our Production environment each calendar year  (excluding scheduled maintenance), with both Production and Sandbox endpoints engineered  for low latency and high throughput. Our platform is continuously monitored 24×7 via automated  health checks and alerting systems, ensuring rapid detection and resolution of any issues.  For planned maintenance—such as security patches, capacity upgrades, or feature deployments  —we will give you at least 48 hours’ advance notice, and schedule work during off-peak IST hours  to minimize any impact on your operations. In the unlikely event of an unplanned outage (due to  hardware failures, network disruptions, or emergency updates), our infrastructure team will  spring into action to restore service as swiftly as possible. We will follow up with you via email or  our status portal, providing a concise incident report that outlines root cause, affected services,  and steps taken to prevent recurrence.  Except where a separate, written Service Level Agreement governs remedies, Mpluse shall not  be liable for any direct, indirect, incidental, or consequential damages resulting from any service  interruption or degradation. This Service Levels & Availability commitment underscores our  promise to keep your applications running reliably—so you can focus on building great financial  experiences.`,
    }
];

export default termsData;



























// const termsData = [
//         {
//             title: "1. Use of Services",
//             content: "You agree to use Mpluse for lawful purposes only and in a way that does not infringe the rights of others.",
//         },
//         {
//             title: "2. Account Responsibility",
//             content: "You are responsible for maintaining the confidentiality of your account and password.",
//         },
//         {
//             title: "3. Payments & Refunds",
//             content: "All payments are final. Refunds are only issued if required by law or as per our refund policy.",
//         },
//         {
//             title: "4. Limitation of Liability",
//             content: "Mpluse is not liable for any damages or losses resulting from your use of our platform.",
//         },
//         {
//             title: "5. Changes to Terms",
//             content: "We may update these Terms anytime. Continued use of the service means you accept the new terms.",
//         },
//         {
//             title: "6. Contact",
//             content: "If you have any questions, contact us at support@mpluse.in",
//         },
//     ];
    
//     export default termsData;