// src/data/termsData.js

import { title } from "framer-motion/client";




const termsData = [
    {
        title: "1. Acceptance of Terms",
        content: `By accessing or using any of Mpluse Fintech Private Limited’s (“Mpluse, ” “we, ” “us, ” or “our”) services—including the dashboard, developer portal, sandbox environment, APIs, mobile applications, or any related interfaces—you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions and our Privacy Policy. Your use of Mpluse’s services constitutes your express acceptance of these terms. If you do not agree with any provision herein, you must immediately discontinue all access to and use of our services. These Terms, together with any documents they expressly incorporate, form the entire agreement between you and Mpluse regarding your use of the services, superseding any prior understandings or agreements.`,
    },
    {
        title: "2. Definitions",
        content: `In these Terms and Conditions, “Services” means all offerings made available by Mpluse Fintech Private Limited—whether the dashboard, developer portal, sandbox environment, RESTful APIs, webhooks, mobile applications or any related features. “You” or “User” refers to any individual or legal entity that registers for or otherwise accesses and uses the Services, and your “Account” is the user profile you create (including your unique login credentials, configuration settings, and profile information) to access those Services. “Credentials” are the API keys, secret keys, tokens or passwords issued or generated by Mpluse for authenticating your API calls, while “Documentation” comprises the technical guides, reference manuals, sample integrations, SDKs and other materials provided by Mpluse to help you integrate with and use our Infrastructure. All data, content or information you submit, transmit or process through the Services—such as transaction details, customer records or metadata—is collectively your “User Data, ” and any non-public information shared between you and Mpluse—such as business plans, technical specifications or pricing—constitutes “Confidential Information.” These Terms (including any documents they expressly incorporate by reference, like our Privacy Policy or applicable Service Level Agreements) became binding on the “Effective Date, ” which is the date you first accepted them or the date they were first made available to you, whichever occurs earlier. Finally, any claim, controversy or disagreement arising out of or relating to these Terms or your use of the Services is referred to as a “Dispute.”`,
    },
    {
        title: "3. Eligibility & Account Registration",
        content: `To access and use Mpluse’s API infrastructure, you must be either (a) a legally registered business entity in India or (b) an individual aged 18 years or older acting in connection with your professional or commercial activities. By registering for an account, you represent and warrant that you meet these eligibility requirements and possess the legal authority to bind your organization to these Terms and Conditions. Registration takes place through our developer portal, where you will be asked to provide accurate and complete information, including your full name, business name, registered address, email address, and any KYC/AML documentation required under applicable laws and RBI/NPCI guidelines. You agree to maintain and promptly update your account information— such as contact details and bank account data—so that we can continue to provide you with secure and uninterrupted service. Upon submission, Mpluse reserves the right to verify your identity and supporting documents before activating your account. We may also perform background checks or request additional information at any time to ensure compliance with our policies and regulatory obligations. Account activation, suspension, or termination decisions rest solely with Mpluse, and we will notify you of any change in status via the email address associated with your account. API Access, Keys & Security Once your account is active, you will receive unique API credentials (keys and tokens) and access to the sandbox environment for testing. It is your responsibility to safeguard these credentials and to immediately inform Mpluse of any unauthorized use or potential security breach. You may not share your credentials with any third party or use them for purposes outside the scope of our services. Failure to adhere to these requirements may result in suspension or revocation of your access. `,
    },
    {
        title: "4. API Access, Keys & Security",
        content: `When your Mpluse account is approved, you will receive a pair of unique API credentials—an API Key and Secret—along with access to separate sandbox and production endpoints. These credentials authenticate every request you make and must be included in each API call according to our documentation. You are solely responsible for safeguarding your API Key and Secret: never embed them in client‐side code, public repositories, or URLs. If you believe your credentials have been compromised, you must immediately revoke them via the developer portal and notify us at security@mpluse.in so we can investigate and issue replacements. All API traffic is encrypted in transit using TLS 1.2 or higher, and access is further protected by anti‐replay measures and rate limiting. Mpluse logs every request, including timestamp, origin IP, endpoint accessed, and response status, to help detect unusual patterns or potential abuse. We recommend rotating your API Secret on a regular cadence (e.g. every 90 days) and after any personnel change. Mpluse reserves the right to suspend or revoke any credentials at our discretion—particularly if we detect suspicious activity or a breach of these Terms. By using our APIs, you agree to follow these security practices and cooperate fully with any investigation into unauthorized access.`,
    },
    {
        title: "5. Permitted Use of Services",
        content: `Your use of Mpluse’s API-based Services is strictly limited to integrating, developing, testing, and operating your own business applications or delivering direct value to your end customers. Through our published RESTful endpoints, you may initiate and reconcile IMPS, UPI, and BBPS payouts and collections, manage virtual wallet balances, retrieve transaction histories and realtime analytics, and generate compliance or reconciliation reports exactly as described in our Documentation. All requests must be authenticated with your issued API credentials and must adhere to our specified rate limits, TLS encryption, anti-CSRF tokens, and logging controls. You may use these Services only for lawful business purposes and in full compliance with all applicable laws and regulations, including KYC/AML requirements, RBI/NPCI guidelines, and the Digital Personal Data Protection Act, 2023. Any attempt to reverse-engineer our APIs, scrape or cache data beyond permitted limits, resell or sublicense the Services as a standalone product, overload or disrupt our infrastructure, or facilitate unlawful activity is strictly prohibited and may result in immediate suspension or termination of your access. If you are uncertain whether a specific integration or workflow is permitted, please review our Documentation or contact support@mpluse.in for clarification before proceeding.`,
    },
    {
        title: "6. Prohibited Activities",
        content: `You agree not to use Mpluse’s Services for any unlawful or abusive purpose, and in particular you will not (a) attempt to gain unauthorized access to our systems, endpoints or data; (b) reverse-engineer, decompile or disassemble any portion of our APIs or underlying software; (c) scrape, crawl, cache or mine any data beyond the limits permitted by our rate limits and Documentation; (d) submit false or fraudulent KYC, transaction or identity information; (e) facilitate money laundering, terrorism financing or other illicit activity; (f) overload, disrupt or impair the integrity or performance of our infrastructure (including by launching denial-ofservice attacks); (g) resell, sublicense or bundle the Services as a standalone product; (h) use automated means to create or manage multiple accounts without our prior written consent; or (i) send spam, phishing or unsolicited marketing communications via our platform. Any prohibited conduct may result in immediate suspension or termination of your access and may expose you to legal liability`,
    },
    {
        title: "Service Levels & Availability",
        content: ` Mpluse is dedicated to providing a robust, always-on API infrastructure for your Banking-as-a Service needs. We target 99.9% uptime on our Production environment each calendar year  (excluding scheduled maintenance), with both Production and Sandbox endpoints engineered  for low latency and high throughput. Our platform is continuously monitored 24×7 via automated  health checks and alerting systems, ensuring rapid detection and resolution of any issues.  For planned maintenance—such as security patches, capacity upgrades, or feature deployments  —we will give you at least 48 hours’ advance notice, and schedule work during off-peak IST hours  to minimize any impact on your operations. In the unlikely event of an unplanned outage (due to  hardware failures, network disruptions, or emergency updates), our infrastructure team will  spring into action to restore service as swiftly as possible. We will follow up with you via email or  our status portal, providing a concise incident report that outlines root cause, affected services,  and steps taken to prevent recurrence.  Except where a separate, written Service Level Agreement governs remedies, Mpluse shall not  be liable for any direct, indirect, incidental, or consequential damages resulting from any service  interruption or degradation. This Service Levels & Availability commitment underscores our  promise to keep your applications running reliably—so you can focus on building great financial  experiences.`,
    },
    {
        title: "Fees, Billing & Payment Terms",
        content: ` Mpluse charges for API usage and related Services in accordance with the pricing schedule  agreed upon at the time of your subscription. All fees are denominated in Indian Rupees (INR)  and are exclusive of any applicable taxes, duties or levies, which will be added to your invoice as  required by law. We issue invoices on a monthly basis—in arrears—within five (5) business days  following the end of each billing cycle. Payment of each invoice is due within fifteen (15)  calendar days of the invoice date and may be made via electronic funds transfer or any other  payment method we support.  If payment is not received by the due date, Mpluse reserves the right to suspend or terminate  your access to the Services, and to charge interest on the outstanding amount at a rate of 1.5%  per month (or the maximum rate permitted by law, if lower), calculated daily from the due date  until payment is received in full. You may dispute any invoiced amount by notifying our billing  team at billing@mpluse.in within ten (10) business days of invoice issuance; undisputed portions  of the invoice must still be paid when due. Upon receipt of a valid dispute, we will investigate  promptly and adjust your invoice if an error is confirmed. All billing terms hereunder are subject to the Digital Personal Data Protection Act, 2023; the  Information Technology Act, 2000; and any relevant RBI/NPCI guidelines. Continued use of the  Services after failure to pay any undisputed fee constitutes acceptance of any late charges and  authorizes Mpluse to collect all amounts due, including collection costs. If you have questions  regarding your invoice or payment options, please contact billing@mpluse.in.`,
    },
    {
        title: " Intellectual Property Rights",
        content: `All intellectual property rights in and to Mpluse’s Services, including but not limited to the API endpoints, software, source code, object code, designs, documentation, data models, trademarks, logos, and trade names, are and will remain the exclusive property of Mpluse Fintech Private Limited or its licensors. Subject to your compliance with these Terms, Mpluse grants you a limited, revocable, non-exclusive, non-transferable license to access and use the Services solely to build, test, and operate your own applications as permitted herein. You may not copy, modify, distribute, sublicense, reverse-engineer, decompile, or otherwise attempt to derive source code from any part of the Services, nor may you remove or obscure any proprietary notices. You retain all right, title, and interest in and to any data or content you submit, transmit, or process through the Services (“User Data”), and you grant Mpluse a worldwide, royalty-free, perpetual, irrevocable license to use, reproduce, modify, and display such User Data solely to provide, maintain, and improve the Services. Any suggestions, feedback, or recommendations you provide regarding the Services will be deemed non-confidential and will become the exclusive property of Mpluse, which may use them without restriction. Nothing in these Terms grants you any rights to Mpluse’s patents, trademarks, service marks, or other proprietary rights, except as expressly set forth herein. All rights not expressly granted are reserved by Mpluse and its licensors.`,
    },
    {
        title: "Confidentiality & Data Protection",
        content: `Both you and Mpluse agree to treat as strictly confidential any non-public information  exchanged in connection with these Terms (“Confidential Information”). This includes, but is not  limited to, business plans, financial data, technical designs, API keys, and integration details. You  will not disclose, reproduce, or use Mpluse’s Confidential Information for any purpose other  than to consume the Services, and you will implement at least the same level of care to protect  it as you do your own confidential data.  Mpluse implements robust technical and organizational safeguards to protect your User Data  and Confidential Information. All data in transit is secured using TLS 1.2+ and data at rest is  encrypted with AES-256 under our cloud provider’s Key Management Service. Access to systems  and data is restricted by role-based permissions, multi-factor authentication, and detailed audit  logs. We perform regular vulnerability scans, annual penetration tests, and 24×7 monitoring to  detect and remediate threats. All processing adheres to the Information Technology Act, 2000;  the Digital Personal Data Protection Act, 2023; and RBI/NPCI guidelines.  Where we engage third-party processors—such as cloud hosts, payment gateways, or analytics  providers—they must enter into Data Processing Agreements mandating confidentiality, limited use, and equivalent security controls. In the event of any suspected data breach or unauthorized  disclosure of Confidential Information, we will notify you promptly in accordance with our Data  Breach Notification procedures. These measures ensure that both your data and Mpluse’s  proprietary information remain protected at every layer of our API-first Banking-as-a-Service  platform.`,
    },
    {
        title: "Compliance with Laws",
        content: `Both you and Mpluse must fully comply with all applicable KYC/AML laws and RBI/NPCI regulations. As part of your onboarding, you will be required to furnish accurate and up-to-date KYC documentation—such as PAN, Aadhaar, company incorporation certificates, and proof of address—before we activate your account. Mpluse will conduct due-diligence checks, verify your identity, and continuously monitor transactions for suspicious patterns in accordance with the Prevention of Money-Laundering Act, 2002; the Information Technology Act, 2000; the Digital Personal Data Protection Act, 2023; and all relevant RBI circulars and NPCI guidelines. We reserve the right to file Suspicious Transaction Reports (STRs) with the Financial Intelligence Unit–India (FIU-IND) and to take immediate action—up to suspension or termination of your access—if you fail to meet these requirements or if we detect any non-compliant activity. Your ongoing adherence to these standards is essential to maintaining secure, lawful access to Mpluse’s Banking-as-a-Service platform.`,
    },
    {
        title: " Warranty Disclaimer",
        content: ` To the fullest extent permitted by law, Mpluse provides its Services “as is” and “as available,”  without any warranties or representations, whether express or implied. Mpluse disclaims all  implied warranties of merchantability, fitness for a particular purpose, title and non infringement. While we use commercially reasonable efforts to maintain security, performance  and uptime, we do not guarantee that the Services will be uninterrupted, error-free or  completely secure, nor that any results or reports generated through the Services will be  accurate or reliable. Mpluse also makes no warranty regarding any third-party content,  integrations or dependencies. Your use of the Services is at your sole risk, and you are  responsible for verifying any output or data before relying on it. In no event shall Mpluse be  liable for any direct, indirect, incidental, consequential, special or punitive damages arising out  of or related to the Services, even if advised of the possibility of such damages.`,
    },
    {
        title: "Limitation of Liability",
        content: ` To the maximum extent permitted by law, neither you nor Mpluse will be liable to the other for any indirect, incidental, consequential, special or punitive damages—such as loss of profits, loss of revenue, loss of business opportunity or loss of data—arising out of or relating to these Terms or your use of the Services, even if the possibility of such damages has been advised. Mpluse’s aggregate liability for any claim arising under or in connection with these Terms shall in no event exceed the total fees paid by you to Mpluse in the twelve (12) months preceding the event giving rise to the claim. Notwithstanding the foregoing, nothing in this clause shall limit liability for death or personal injury resulting from negligence, or for any liability which cannot be excluded or limited under applicable law. This limitation applies equally to Mpluse’s officers, directors, employees, agents, affiliates and licensors.`,
    },
    {
        title: "Indemnification",
        content: ` You agree to indemnify, defend and hold harmless Mpluse Fintech Private Limited, its officers,  directors, employees, agents and affiliates (collectively, “Mpluse Indemnitees”) from and against  any and all losses, liabilities, damages, fines, penalties, costs and expenses (including reasonable  attorneys’ fees) arising out of or relating to: (a) your use of or inability to use the Services; (b) any  breach or alleged breach by you of these Terms; (c) your violation of applicable laws, regulations  or third-party rights; or (d) any data, content or materials you submit, transmit or process  through the Services. Mpluse reserves the right, at its sole expense, to assume the exclusive defense and control of  any matter subject to indemnification, and you agree to cooperate with Mpluse’s reasonable  requests in connection with such defense. You may not settle any indemnified claim without  Mpluse’s prior written consent. This indemnification obligation will survive any termination of  these Terms or your access to the Services.`,
    },
    {
        title: "Termination & Suspension of Access",
        content: `Mpluse reserves the right to suspend or terminate your access to the Services at any time and without liability if we believe, in our sole discretion, that you have violated these Terms (including non-payment of fees), engaged in prohibited activities, or if required by law, court order, or regulatory authority. In the event of suspension, we will notify you via the email address associated with your account and, whenever practicable, provide you with a reasonable opportunity to cure any breach. For termination, we will send a written notice at least seven (7) days in advance, unless immediate termination is necessary to protect our platform or comply with legal obligations. Upon suspension or termination, your right to access the Services will immediately cease, though you remain responsible for any outstanding fees or liabilities incurred prior to the effective date. All provisions that by their nature survive—such as Confidentiality & Data Protection, Intellectual Property Rights, Indemnification, Limitation of Liability, and any payment obligations—will continue in full force and effect. If you believe your access has been suspended or terminated in error, please contact us at support@mpluse.in to discuss reinstatement.`,
    },
    {
        title: "Modification of Terms",
        content: `Mpluse may amend or update these Terms and Conditions at any time in its sole discretion. When we make material changes, we will provide you with at least 30 days’ advance notice by posting the updated Terms on our website and sending an email to the address associated with your account. Such notice will specify the effective date of the changes. Your continued access to or use of the Services after the effective date constitutes your acceptance of the revised Terms. If you do not agree with any modification, you must cease all use of the Services and may terminate your account by contacting support@mpluse.in before the new Terms take effect. Minor, non-material corrections (such as typographical fixes) may be implemented immediately without prior notice.`,
    },
    {
        title: "Governing Law & Dispute Resolution",
        content: ` These Terms and your use of Mpluse’s Services shall be governed by and construed in accordance with the laws of India, without regard to its conflict-of-laws principles. In the event of any dispute, claim or controversy arising out of or relating to these Terms or your use of the Services, the parties shall first attempt to resolve the matter amicably through good-faith discussions within thirty (30) days of one party’s written notice of dispute. If the matter remains unresolved after this period, it shall be finally settled by binding arbitration under the Arbitration and Conciliation Act, 1996. The arbitration shall be conducted in Lucknow, India, in the English language, before a sole arbitrator appointed by mutual agreement (or, failing agreement, by the Centre for Arbitration in Lucknow). The arbitrator’s award shall be final and binding on both parties and enforceable in any court of competent jurisdiction. Notwithstanding the foregoing, either party may seek interim injunctive relief in the courts of Lucknow to protect its intellectual property or confidential information.`,
    },
    {
        title: "Contact Information",
        content: `If you have any questions, feedback or require assistance with these Terms, please reach out to us at:`,
    },
    {
        title: " Mpluse Fintech Private Limited",
        content: ` Registered Office: Plot No. 12, Sector 9, Financial District, Hazratganj, Lucknow – 226001, Uttar
 Pradesh, India
 General Support: support@mpluse.in
 Billing Inquiries: billing@mpluse.in
 Security Issues: security@mpluse.in
 Data Protection Officer: privacy@mpluse.in
 Phone: +91 522 123 4567
 Our team is available Monday–Friday, 9:00 AM–6:00 PM IST, and will acknowledge receipt of
 your inquiry within two business days`,
    }
];

export default termsData;



























// const termsData = [
//         {
//             title: "1. Use of Services",
//             content: "You agree to use Mpluse for lawful purposes only and in a way that does not infringe the rights of others.",
//         },
//         {
//             title: "2. Account Responsibility",
//             content: "You are responsible for maintaining the confidentiality of your account and password.",
//         },
//         {
//             title: "3. Payments & Refunds",
//             content: "All payments are final. Refunds are only issued if required by law or as per our refund policy.",
//         },
//         {
//             title: "4. Limitation of Liability",
//             content: "Mpluse is not liable for any damages or losses resulting from your use of our platform.",
//         },
//         {
//             title: "5. Changes to Terms",
//             content: "We may update these Terms anytime. Continued use of the service means you accept the new terms.",
//         },
//         {
//             title: "6. Contact",
//             content: "If you have any questions, contact us at support@mpluse.in",
//         },
//     ];
    
//     export default termsData;